[build]
    # we put server/functions inside react so we can do a deploy button for both 
    # netlify only allows a single deploy button (and related toml)
    functions = "server/functions"

    # react and subfolders are the only parts that can be netlify deployed it is our base
    base = "./react/"

    command = "npm run build"

    publish = "build/"

[build.environment]
    # suppress failures for for build warnings
    CI = "false"

[template.environment]
    DAILY_API_KEY = "e20e11c2e1fe20a5acead7a469e231aea2f5e3af0d714665af2fbcca70a3d540"